name: PIPELINE-INTEGRADA

on:
  workflow_dispatch:

jobs:
  inspecao:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar Yarn
        run: npm install -g yarn
      - name: Instalar dependências
        run: yarn install
      - name: Checar padronização do código (lint)
        run: yarn lint

  unidade:
    runs-on: ubuntu-latest
    needs: inspecao
    steps:
      - uses: actions/checkout@v4
      - name: Instalar Yarn
        run: npm install -g yarn
      - name: Instalar dependências
        run: yarn install
      - name: Executar testes unitários
        run: yarn test

  e2e:
    runs-on: ubuntu-latest
    needs: unidade
    steps:
      - uses: actions/checkout@v4
      - name: Instalar Yarn
        run: npm install -g yarn
      - name: Instalar dependências
        run: yarn install
      - name: Instalar Playwright e navegadores
        run: npx playwright install --with-deps
      - name: Executar testes e2e
        run: yarn e2e
      - uses: actions/upload-artifact@v4
        with:
          name: relatorio-e2e
          path: ./playwright-report
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: e2e
    steps:
      - name: Simular Deploy
        run: echo "Deploy simulado com sucesso!"
